### ISSUE TITLE
SQL Lab design review tasks

### ISSUE THREAD

**Issue by ascott** [airbnb/caravel#1001]
- [x]  For the top naviation bar, use a 4 pixel underline to highlight which tab is active - alanna

- [ ] Move Alpha away from the SQL Lab logo to the top navigation bar

- [ ] Use fewer icons and more text for buttons and call to actions

- [ ]  use 50/50 Split between the SQL editor box and the results area to give editor more space - alanna

- [ ] in query history table, use dropdown button with list of actions rather than icons

- [x] use blue from airpal as default btn color - alanna

- [ ] get rid of gray background on sql editor  - alanna

- [x] subtle rounded corner for buttons? try 2px.  - alanna

- [x] use airpal blue for link color  - alanna

- [ ] review tab highlight colors and hover, maybe use airpal blue color for text  - alanna

- [ ] bring data preview into result/history area, or on right hand side, don't use overlay

- [ ] disable schema/table selects until db is selected

- [ ] add dropdown menu to SQL Lab top menu item >>> query editor, saved queries

- [ ] we should strip airbnb brand colors from the visualizations and use category 21 colors for now (best practice)

cc @bkyryliuk @mistercrunch @jefffeng
