### ISSUE TITLE
Add an endpoint to warm up the cache.

### ISSUE THREAD

**Issue by bkyryliuk** [airbnb/caravel#1021]
The api would receive the dashboard id and warm up the cache.

- [ ]  Refactor the explore method into separate html and csv endpoint
- [x] Add `get_viz` to the `Slice` and refactore the explore endpoint to use it
- [x] Implement `warmup_cache_dashboard/<dashboard_id>` endpoint for the dashboard
- [x] Implement `warmup_cache_table/<table_id>` endpoint for the table

The viz creation should look like this in the explore view:
```
if slice:
    viz = slice.get_viz(form_data)
else
    viz = viz.viz_types[viz_type](form_data)
```
Cache update for the dashboard:
```
for slice in dashboard:
    viz = slice.get_viz(force=True)
    viz.get_json()
```
similarly for a table
Cache update for the dashboard:
```
for slice in table:
    viz = slice.get_viz(force=True)
    viz.get_json()
```

**Comment by mistercrunch** [comment]
I'd like to remove all references to `self.slice` from the viz object.

I think it's just a matter of passing the cache_timeout as its own argument, or bundling it along with the rest of form_data
