### ISSUE TITLE
Implement remote query execution

### ISSUE THREAD

**Issue by bkyryliuk** [airbnb/caravel#746]
User celery to execute the SQL queries remotely.
The branch the code is worked on:
https://github.com/airbnb/caravel/tree/celery

PR: https://github.com/airbnb/caravel/pull/759

TODO:

- [x] Add celery worker
- [x] Execute the query on the celery worker
- [x] Add integration test that runs celery worker and check the communication between celery and webserver
- [x] Add query model and use it in the worker
- [x] Wrap the queries in celery into create as statement
