### ISSUE TITLE
SQL Lab [Basic] - Beta of rich SQL editor as part of Caravel

### ISSUE THREAD

**Issue by mistercrunch** [airbnb/caravel#801]
### Basic [Beta]
- [x] Per database permissions (Create a permission object.  Right now it is per table) - Bogdan
- [x]  Create Table As (asynchronous query) - Bogdan
- [x] Download to .CSV and .JSON - Bogdan
- [x] Surface partitions metadata - Max
- [x] UI/UX for viewing table schema - Max
- [x] UI/UX for viewing table details - Max 
- [x] UI/UX for viewing table preview - Max
- [ ] Rich text editor (folding, auto-complete, etc.) - Max
- [x] Query Search - All Queries, My Saved Queries, My Recent Queries - Alanna
- [x] Define and implement SQL Lab to Caravel Visualize flow - Alanna, Meredith

### Sub tasks
- [x] adapt to latest linting rules
- [x] integrate with async
- [x] move timer to its own component
- [x] show a warning when row limit is hit

**Comment by mistercrunch** [comment]
WIP PR:
https://github.com/airbnb/caravel/pull/514

**Comment by jefffeng** [comment]
@mistercrunch, let's break down the rough features of the Caravel SQL Editor into separate issues.

**Comment by bkyryliuk** [comment]
Rich text editor (folding, auto-complete, etc.) - the only feature left and it has it's on FR.
