### ISSUE TITLE
[ui] fix /caravel/theme

### ISSUE THREAD

**Issue by ascott** [airbnb/caravel#897]
it is very broken after last ui update.

- [x] make buttons look more clearly like buttons (background-color? border? box-shadow?)
- [x] make links look more like links (color? underline?)
- [x] roll back to previous alert colors? (I tweaked them recently and liked them better than what there now)
- [x] Slice title in explore view should maybe wrap somehow or the right controls pushed down...
- [x] make tabs look like tabs
- [x]  controls' info-bubbles with tooltip in the explore view are gone
- [x] Loading spinner doesn't show in explore view
- [x] Explore view fails hard when following a table link (when no slices have been defined yet)

**Comment by mistercrunch** [comment]
Still a very net positive set of changes!

A few notes:
* make buttons look more clearly like buttons (background-color? border? box-shadow?)
* make links look more like links (color? underline?)
* roll back to previous alert colors? (I tweaked them recently and liked them better than what there now)
* Slice title in explore view should maybe wrap somehow or the right controls pushed down...

**Comment by mistercrunch** [comment]
Also just noticed that the controls' info-bubbles with tooltip in the explore view are gone....

**Comment by mistercrunch** [comment]
Loading spinner doesn't show in explore view

**Comment by mistercrunch** [comment]
Explore view fails hard when following a table link (when no slices have been defined yet)
